    language: python # => 1

    python: # => 2

      - "3.8"

    services: # => 3

      - mysql

    env: # => 4

      -DJANGO=3.1 DB=mysql
    install: # => 5

      - pip install -r requirements.txt
      - pip install coveralls

    before_script: # => 6

      - mysql -e 'create database test;' -u root
    script: # => 7

      - python manage.py test
      - coverage run --source=home manage.py test users
    after_success: 
    - coveralls --exclude-pattern=*.txt *.html *.js *.css *.sqlite3
