language: python

python:
  - "3.8"
  - "3.7"
  - "3.6"
    
env:
  - - DJANGO=3.1

services:
  - mysql

install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q -e . --use-mirrors

script:
  - python manage.py test
  

    
