language: python

python:
  - "3.8"
  - "3.7"
  - "3.6"
    
env:
  - DJANGO=3.1

services:
  - mysql

install:
  - pip install -q Django==$DJANGO
  - pip install django-crispy-forms


script:
  - python manage.py test
  

    
