# Generated by Django 3.0.6 on 2020-08-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=256)),
                ('student_number', models.IntegerField(max_length=8, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(max_length=256)),
                ('course_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('students', models.ManyToManyField(to='Database.Student')),
            ],
        ),
    ]
